### ISSUE TITLE
unsafe repository

### ISSUE THREAD

**Issue by NaveenKumarThangamuthu** [youyo/sync-up-to-codecommit-action#2]
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
![Screenshot from 2022-04-29 11-15-08](https://user-images.githubusercontent.com/78854774/165890720-fb169ac7-ce39-4251-bffa-ee90aff575f8.png)

**Comment by bloodyburger** [comment]
I added like below but doesn't work, same error
```
      - name: Sync up to CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@v1
        with:
          repository_name: xxxx
          aws_region: us-west-1
      - name: setup git config
        run: git config --global --add safe.directory /github/workspace  
```
